#ifndef EYERPLAYERLIB_GLOBAL_H
#define EYERPLAYERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EYERPLAYERLIB_LIBRARY)
#  define EYERPLAYERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EYERPLAYERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EYERPLAYERLIB_GLOBAL_H
