/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzsin_eyerplayer_jni_EyerPlayerJNI */

#ifndef _Included_com_zzsin_eyerplayer_jni_EyerPlayerJNI
#define _Included_com_zzsin_eyerplayer_jni_EyerPlayerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzsin_eyerplayer_jni_EyerPlayerJNI
 * Method:    eyer_player_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zzsin_eyerplayer_jni_EyerPlayerJNI_eyer_1player_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_zzsin_eyerplayer_jni_EyerPlayerJNI
 * Method:    eyer_player_uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyerplayer_jni_EyerPlayerJNI_eyer_1player_1uninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyerplayer_jni_EyerPlayerJNI
 * Method:    eyer_player_set_url
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyerplayer_jni_EyerPlayerJNI_eyer_1player_1set_1url
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_zzsin_eyerplayer_jni_EyerPlayerJNI
 * Method:    eyer_player_play
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyerplayer_jni_EyerPlayerJNI_eyer_1player_1play
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyerplayer_jni_EyerPlayerJNI
 * Method:    eyer_player_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyerplayer_jni_EyerPlayerJNI_eyer_1player_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyerplayer_jni_EyerPlayerJNI
 * Method:    eyer_player_pause
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyerplayer_jni_EyerPlayerJNI_eyer_1player_1pause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_zzsin_eyerplayer_jni_EyerPlayerJNI
 * Method:    eyer_player_resume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_zzsin_eyerplayer_jni_EyerPlayerJNI_eyer_1player_1resume
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
